/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "handyplug/handyplug.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(handyplug_Ok, handyplug_Ok, AUTO)

PB_BIND(handyplug_Error, handyplug_Error, AUTO)

PB_BIND(handyplug_Ping, handyplug_Ping, AUTO)

PB_BIND(handyplug_RequestServerInfo, handyplug_RequestServerInfo, AUTO)

PB_BIND(handyplug_ServerInfo, handyplug_ServerInfo, AUTO)

PB_BIND(handyplug_LinearCmd, handyplug_LinearCmd, AUTO)

PB_BIND(handyplug_LinearCmd_Vector, handyplug_LinearCmd_Vector, AUTO)

PB_BIND(handyplug_Message, handyplug_Message, 2)

PB_BIND(handyplug_Payload, handyplug_Payload, AUTO)

#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif
