/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTO_SETTING_PB_H_INCLUDED
#define PB_PROTO_SETTING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Setting_Wifi {
    char ssid[65];
    char password[65];
    int32_t static_ip;
    int32_t gateway;
    int32_t dns;
    bool enable_soft_ap;
    char soft_ap_ssid[65];
    char soft_ap_password[65];
    int32_t soft_ap_ip;
    int32_t tcp_port; /* TCP端口号 */
    int32_t udp_port; /* UDP端口号 */
} Setting_Wifi;

typedef struct _Setting_Servo {
    int32_t A_SERVO_PIN;
    int32_t B_SERVO_PIN;
    int32_t C_SERVO_PIN;
    int32_t D_SERVO_PIN;
    int32_t E_SERVO_PIN;
    int32_t F_SERVO_PIN;
    int32_t G_SERVO_PIN;
    int32_t A_SERVO_PWM_FREQ;
    int32_t B_SERVO_PWM_FREQ;
    int32_t C_SERVO_PWM_FREQ;
    int32_t D_SERVO_PWM_FREQ;
    int32_t E_SERVO_PWM_FREQ;
    int32_t F_SERVO_PWM_FREQ;
    int32_t G_SERVO_PWM_FREQ;
    int32_t A_SERVO_ZERO;
    int32_t B_SERVO_ZERO;
    int32_t C_SERVO_ZERO;
    int32_t D_SERVO_ZERO;
    int32_t E_SERVO_ZERO;
    int32_t F_SERVO_ZERO;
    int32_t G_SERVO_ZERO;
    float L0_SCALE;
    float L1_SCALE;
    float L2_SCALE;
    float R0_SCALE;
    float R1_SCALE;
    float R2_SCALE;
    float L0_LEFT;
    float L0_RIGHT;
    float L1_LEFT;
    float L1_RIGHT;
    float L2_LEFT;
    float L2_RIGHT;
    float R0_LEFT;
    float R0_RIGHT;
    float R1_LEFT;
    float R1_RIGHT;
    float R2_LEFT;
    float R2_RIGHT;
    bool L0_REVERSE;
    bool L1_REVERSE;
    bool L2_REVERSE;
    bool R0_REVERSE;
    bool R1_REVERSE;
    bool R2_REVERSE;
    float MODE;
} Setting_Servo;

typedef struct _Setting_Temperature {
    int64_t deviceAddress1;
    int64_t deviceAddress2;
    int64_t deviceAddress3;
} Setting_Temperature;

typedef struct _Setting_mDNS {
    char name[65];
} Setting_mDNS;

typedef struct _Setting_LED {
    bool enable; /* 是否开启led */
} Setting_LED;

typedef struct _Setting_Decoy {
    int32_t ADC_PIN;
    int32_t MOD1_PIN;
    int32_t MOD2_PIN;
    int32_t MOD3_PIN;
} Setting_Decoy;

typedef struct _Setting_ZDT_HomeParam {
    int32_t home_speed; /* 回零速度 */
    int32_t home_timeout; /* 回零超时时间 */
    int32_t home_collide_speed; /* 堵转速度阈值 */
    int32_t home_collide_current; /* 堵转电流阈值 */
    int32_t home_collide_time; /* 堵转时间阈值 */
    int32_t home_wait_time; /* 单位是s */
} Setting_ZDT_HomeParam;

typedef struct _Setting_ZDT {
    float Kp;
    float Ki;
    float Kd;
    float IMax;
    bool useAutoHome; /* 是否自动回零，不开需要用户自己确保上电时滑块已经在最低点 */
    Setting_ZDT_HomeParam home_param;
    bool enableDebug;
} Setting_ZDT;

typedef struct _Setting_MIT {
    float Kp_a;
    float Ki_a;
    float Kd_a;
    float offset_a; /* 角度，不是弧度 */
    float Kp_b;
    float Ki_b;
    float Kd_b;
    float offset_b; /* 角度，不是弧度 */
    float Kp_c;
    float Ki_c;
    float Kd_c;
    float offset_c; /* 角度，不是弧度 */
    float Kp_d;
    float Ki_d;
    float Kd_d;
    float offset_d; /* 角度，不是弧度 */
    float Kp_e;
    float Ki_e;
    float Kd_e;
    float offset_e; /* 角度，不是弧度 */
    float Kp_f;
    float Ki_f;
    float Kd_f;
    float offset_f; /* 角度，不是弧度 */
} Setting_MIT;

typedef struct _Setting {
    Setting_Wifi wifi;
    Setting_Servo servo;
    /* deprecated */
    Setting_Temperature temp;
    Setting_mDNS mdns;
    Setting_LED led;
    Setting_Decoy decoy;
    Setting_ZDT zdt;
    Setting_MIT mit;
} Setting;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Setting_init_default                     {Setting_Wifi_init_default, Setting_Servo_init_default, Setting_Temperature_init_default, Setting_mDNS_init_default, Setting_LED_init_default, Setting_Decoy_init_default, Setting_ZDT_init_default, Setting_MIT_init_default}
#define Setting_Wifi_init_default                {"", "", 0, 0, 0, 0, "", "", 0, 0, 0}
#define Setting_Servo_init_default               {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Setting_Temperature_init_default         {0, 0, 0}
#define Setting_mDNS_init_default                {""}
#define Setting_LED_init_default                 {0}
#define Setting_Decoy_init_default               {0, 0, 0, 0}
#define Setting_ZDT_init_default                 {0, 0, 0, 0, 0, Setting_ZDT_HomeParam_init_default, 0}
#define Setting_ZDT_HomeParam_init_default       {0, 0, 0, 0, 0, 0}
#define Setting_MIT_init_default                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Setting_init_zero                        {Setting_Wifi_init_zero, Setting_Servo_init_zero, Setting_Temperature_init_zero, Setting_mDNS_init_zero, Setting_LED_init_zero, Setting_Decoy_init_zero, Setting_ZDT_init_zero, Setting_MIT_init_zero}
#define Setting_Wifi_init_zero                   {"", "", 0, 0, 0, 0, "", "", 0, 0, 0}
#define Setting_Servo_init_zero                  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Setting_Temperature_init_zero            {0, 0, 0}
#define Setting_mDNS_init_zero                   {""}
#define Setting_LED_init_zero                    {0}
#define Setting_Decoy_init_zero                  {0, 0, 0, 0}
#define Setting_ZDT_init_zero                    {0, 0, 0, 0, 0, Setting_ZDT_HomeParam_init_zero, 0}
#define Setting_ZDT_HomeParam_init_zero          {0, 0, 0, 0, 0, 0}
#define Setting_MIT_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Setting_Wifi_ssid_tag                    1
#define Setting_Wifi_password_tag                2
#define Setting_Wifi_static_ip_tag               3
#define Setting_Wifi_gateway_tag                 4
#define Setting_Wifi_dns_tag                     5
#define Setting_Wifi_enable_soft_ap_tag          6
#define Setting_Wifi_soft_ap_ssid_tag            7
#define Setting_Wifi_soft_ap_password_tag        8
#define Setting_Wifi_soft_ap_ip_tag              9
#define Setting_Wifi_tcp_port_tag                10
#define Setting_Wifi_udp_port_tag                11
#define Setting_Servo_A_SERVO_PIN_tag            1
#define Setting_Servo_B_SERVO_PIN_tag            2
#define Setting_Servo_C_SERVO_PIN_tag            3
#define Setting_Servo_D_SERVO_PIN_tag            4
#define Setting_Servo_E_SERVO_PIN_tag            26
#define Setting_Servo_F_SERVO_PIN_tag            27
#define Setting_Servo_G_SERVO_PIN_tag            44
#define Setting_Servo_A_SERVO_PWM_FREQ_tag       5
#define Setting_Servo_B_SERVO_PWM_FREQ_tag       6
#define Setting_Servo_C_SERVO_PWM_FREQ_tag       7
#define Setting_Servo_D_SERVO_PWM_FREQ_tag       8
#define Setting_Servo_E_SERVO_PWM_FREQ_tag       28
#define Setting_Servo_F_SERVO_PWM_FREQ_tag       29
#define Setting_Servo_G_SERVO_PWM_FREQ_tag       45
#define Setting_Servo_A_SERVO_ZERO_tag           9
#define Setting_Servo_B_SERVO_ZERO_tag           10
#define Setting_Servo_C_SERVO_ZERO_tag           11
#define Setting_Servo_D_SERVO_ZERO_tag           12
#define Setting_Servo_E_SERVO_ZERO_tag           30
#define Setting_Servo_F_SERVO_ZERO_tag           31
#define Setting_Servo_G_SERVO_ZERO_tag           46
#define Setting_Servo_L0_SCALE_tag               13
#define Setting_Servo_L1_SCALE_tag               32
#define Setting_Servo_L2_SCALE_tag               34
#define Setting_Servo_R0_SCALE_tag               33
#define Setting_Servo_R1_SCALE_tag               14
#define Setting_Servo_R2_SCALE_tag               15
#define Setting_Servo_L0_LEFT_tag                16
#define Setting_Servo_L0_RIGHT_tag               17
#define Setting_Servo_L1_LEFT_tag                35
#define Setting_Servo_L1_RIGHT_tag               36
#define Setting_Servo_L2_LEFT_tag                39
#define Setting_Servo_L2_RIGHT_tag               40
#define Setting_Servo_R0_LEFT_tag                37
#define Setting_Servo_R0_RIGHT_tag               38
#define Setting_Servo_R1_LEFT_tag                18
#define Setting_Servo_R1_RIGHT_tag               19
#define Setting_Servo_R2_LEFT_tag                20
#define Setting_Servo_R2_RIGHT_tag               21
#define Setting_Servo_L0_REVERSE_tag             23
#define Setting_Servo_L1_REVERSE_tag             41
#define Setting_Servo_L2_REVERSE_tag             43
#define Setting_Servo_R0_REVERSE_tag             42
#define Setting_Servo_R1_REVERSE_tag             24
#define Setting_Servo_R2_REVERSE_tag             25
#define Setting_Servo_MODE_tag                   22
#define Setting_Temperature_deviceAddress1_tag   1
#define Setting_Temperature_deviceAddress2_tag   2
#define Setting_Temperature_deviceAddress3_tag   3
#define Setting_mDNS_name_tag                    1
#define Setting_LED_enable_tag                   1
#define Setting_Decoy_ADC_PIN_tag                1
#define Setting_Decoy_MOD1_PIN_tag               2
#define Setting_Decoy_MOD2_PIN_tag               3
#define Setting_Decoy_MOD3_PIN_tag               4
#define Setting_ZDT_HomeParam_home_speed_tag     1
#define Setting_ZDT_HomeParam_home_timeout_tag   2
#define Setting_ZDT_HomeParam_home_collide_speed_tag 3
#define Setting_ZDT_HomeParam_home_collide_current_tag 4
#define Setting_ZDT_HomeParam_home_collide_time_tag 5
#define Setting_ZDT_HomeParam_home_wait_time_tag 6
#define Setting_ZDT_Kp_tag                       1
#define Setting_ZDT_Ki_tag                       2
#define Setting_ZDT_Kd_tag                       3
#define Setting_ZDT_IMax_tag                     4
#define Setting_ZDT_useAutoHome_tag              5
#define Setting_ZDT_home_param_tag               6
#define Setting_ZDT_enableDebug_tag              7
#define Setting_MIT_Kp_a_tag                     1
#define Setting_MIT_Ki_a_tag                     2
#define Setting_MIT_Kd_a_tag                     3
#define Setting_MIT_offset_a_tag                 4
#define Setting_MIT_Kp_b_tag                     5
#define Setting_MIT_Ki_b_tag                     6
#define Setting_MIT_Kd_b_tag                     7
#define Setting_MIT_offset_b_tag                 8
#define Setting_MIT_Kp_c_tag                     9
#define Setting_MIT_Ki_c_tag                     10
#define Setting_MIT_Kd_c_tag                     11
#define Setting_MIT_offset_c_tag                 12
#define Setting_MIT_Kp_d_tag                     13
#define Setting_MIT_Ki_d_tag                     14
#define Setting_MIT_Kd_d_tag                     15
#define Setting_MIT_offset_d_tag                 16
#define Setting_MIT_Kp_e_tag                     17
#define Setting_MIT_Ki_e_tag                     18
#define Setting_MIT_Kd_e_tag                     19
#define Setting_MIT_offset_e_tag                 20
#define Setting_MIT_Kp_f_tag                     21
#define Setting_MIT_Ki_f_tag                     22
#define Setting_MIT_Kd_f_tag                     23
#define Setting_MIT_offset_f_tag                 24
#define Setting_wifi_tag                         1
#define Setting_servo_tag                        2
#define Setting_temp_tag                         3
#define Setting_mdns_tag                         4
#define Setting_led_tag                          5
#define Setting_decoy_tag                        6
#define Setting_zdt_tag                          7
#define Setting_mit_tag                          8

/* Struct field encoding specification for nanopb */
#define Setting_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  wifi,              1) \
X(a, STATIC,   REQUIRED, MESSAGE,  servo,             2) \
X(a, STATIC,   REQUIRED, MESSAGE,  temp,              3) \
X(a, STATIC,   REQUIRED, MESSAGE,  mdns,              4) \
X(a, STATIC,   REQUIRED, MESSAGE,  led,               5) \
X(a, STATIC,   REQUIRED, MESSAGE,  decoy,             6) \
X(a, STATIC,   REQUIRED, MESSAGE,  zdt,               7) \
X(a, STATIC,   REQUIRED, MESSAGE,  mit,               8)
#define Setting_CALLBACK NULL
#define Setting_DEFAULT NULL
#define Setting_wifi_MSGTYPE Setting_Wifi
#define Setting_servo_MSGTYPE Setting_Servo
#define Setting_temp_MSGTYPE Setting_Temperature
#define Setting_mdns_MSGTYPE Setting_mDNS
#define Setting_led_MSGTYPE Setting_LED
#define Setting_decoy_MSGTYPE Setting_Decoy
#define Setting_zdt_MSGTYPE Setting_ZDT
#define Setting_mit_MSGTYPE Setting_MIT

#define Setting_Wifi_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   ssid,              1) \
X(a, STATIC,   REQUIRED, STRING,   password,          2) \
X(a, STATIC,   REQUIRED, INT32,    static_ip,         3) \
X(a, STATIC,   REQUIRED, INT32,    gateway,           4) \
X(a, STATIC,   REQUIRED, INT32,    dns,               5) \
X(a, STATIC,   REQUIRED, BOOL,     enable_soft_ap,    6) \
X(a, STATIC,   REQUIRED, STRING,   soft_ap_ssid,      7) \
X(a, STATIC,   REQUIRED, STRING,   soft_ap_password,   8) \
X(a, STATIC,   REQUIRED, INT32,    soft_ap_ip,        9) \
X(a, STATIC,   REQUIRED, INT32,    tcp_port,         10) \
X(a, STATIC,   REQUIRED, INT32,    udp_port,         11)
#define Setting_Wifi_CALLBACK NULL
#define Setting_Wifi_DEFAULT NULL

#define Setting_Servo_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    A_SERVO_PIN,       1) \
X(a, STATIC,   REQUIRED, INT32,    B_SERVO_PIN,       2) \
X(a, STATIC,   REQUIRED, INT32,    C_SERVO_PIN,       3) \
X(a, STATIC,   REQUIRED, INT32,    D_SERVO_PIN,       4) \
X(a, STATIC,   REQUIRED, INT32,    A_SERVO_PWM_FREQ,   5) \
X(a, STATIC,   REQUIRED, INT32,    B_SERVO_PWM_FREQ,   6) \
X(a, STATIC,   REQUIRED, INT32,    C_SERVO_PWM_FREQ,   7) \
X(a, STATIC,   REQUIRED, INT32,    D_SERVO_PWM_FREQ,   8) \
X(a, STATIC,   REQUIRED, INT32,    A_SERVO_ZERO,      9) \
X(a, STATIC,   REQUIRED, INT32,    B_SERVO_ZERO,     10) \
X(a, STATIC,   REQUIRED, INT32,    C_SERVO_ZERO,     11) \
X(a, STATIC,   REQUIRED, INT32,    D_SERVO_ZERO,     12) \
X(a, STATIC,   REQUIRED, FLOAT,    L0_SCALE,         13) \
X(a, STATIC,   REQUIRED, FLOAT,    R1_SCALE,         14) \
X(a, STATIC,   REQUIRED, FLOAT,    R2_SCALE,         15) \
X(a, STATIC,   REQUIRED, FLOAT,    L0_LEFT,          16) \
X(a, STATIC,   REQUIRED, FLOAT,    L0_RIGHT,         17) \
X(a, STATIC,   REQUIRED, FLOAT,    R1_LEFT,          18) \
X(a, STATIC,   REQUIRED, FLOAT,    R1_RIGHT,         19) \
X(a, STATIC,   REQUIRED, FLOAT,    R2_LEFT,          20) \
X(a, STATIC,   REQUIRED, FLOAT,    R2_RIGHT,         21) \
X(a, STATIC,   REQUIRED, FLOAT,    MODE,             22) \
X(a, STATIC,   REQUIRED, BOOL,     L0_REVERSE,       23) \
X(a, STATIC,   REQUIRED, BOOL,     R1_REVERSE,       24) \
X(a, STATIC,   REQUIRED, BOOL,     R2_REVERSE,       25) \
X(a, STATIC,   REQUIRED, INT32,    E_SERVO_PIN,      26) \
X(a, STATIC,   REQUIRED, INT32,    F_SERVO_PIN,      27) \
X(a, STATIC,   REQUIRED, INT32,    E_SERVO_PWM_FREQ,  28) \
X(a, STATIC,   REQUIRED, INT32,    F_SERVO_PWM_FREQ,  29) \
X(a, STATIC,   REQUIRED, INT32,    E_SERVO_ZERO,     30) \
X(a, STATIC,   REQUIRED, INT32,    F_SERVO_ZERO,     31) \
X(a, STATIC,   REQUIRED, FLOAT,    L1_SCALE,         32) \
X(a, STATIC,   REQUIRED, FLOAT,    R0_SCALE,         33) \
X(a, STATIC,   REQUIRED, FLOAT,    L2_SCALE,         34) \
X(a, STATIC,   REQUIRED, FLOAT,    L1_LEFT,          35) \
X(a, STATIC,   REQUIRED, FLOAT,    L1_RIGHT,         36) \
X(a, STATIC,   REQUIRED, FLOAT,    R0_LEFT,          37) \
X(a, STATIC,   REQUIRED, FLOAT,    R0_RIGHT,         38) \
X(a, STATIC,   REQUIRED, FLOAT,    L2_LEFT,          39) \
X(a, STATIC,   REQUIRED, FLOAT,    L2_RIGHT,         40) \
X(a, STATIC,   REQUIRED, BOOL,     L1_REVERSE,       41) \
X(a, STATIC,   REQUIRED, BOOL,     R0_REVERSE,       42) \
X(a, STATIC,   REQUIRED, BOOL,     L2_REVERSE,       43) \
X(a, STATIC,   REQUIRED, INT32,    G_SERVO_PIN,      44) \
X(a, STATIC,   REQUIRED, INT32,    G_SERVO_PWM_FREQ,  45) \
X(a, STATIC,   REQUIRED, INT32,    G_SERVO_ZERO,     46)
#define Setting_Servo_CALLBACK NULL
#define Setting_Servo_DEFAULT NULL

#define Setting_Temperature_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT64,    deviceAddress1,    1) \
X(a, STATIC,   REQUIRED, INT64,    deviceAddress2,    2) \
X(a, STATIC,   REQUIRED, INT64,    deviceAddress3,    3)
#define Setting_Temperature_CALLBACK NULL
#define Setting_Temperature_DEFAULT NULL

#define Setting_mDNS_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   name,              1)
#define Setting_mDNS_CALLBACK NULL
#define Setting_mDNS_DEFAULT NULL

#define Setting_LED_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     enable,            1)
#define Setting_LED_CALLBACK NULL
#define Setting_LED_DEFAULT NULL

#define Setting_Decoy_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    ADC_PIN,           1) \
X(a, STATIC,   REQUIRED, INT32,    MOD1_PIN,          2) \
X(a, STATIC,   REQUIRED, INT32,    MOD2_PIN,          3) \
X(a, STATIC,   REQUIRED, INT32,    MOD3_PIN,          4)
#define Setting_Decoy_CALLBACK NULL
#define Setting_Decoy_DEFAULT NULL

#define Setting_ZDT_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    Kp,                1) \
X(a, STATIC,   REQUIRED, FLOAT,    Ki,                2) \
X(a, STATIC,   REQUIRED, FLOAT,    Kd,                3) \
X(a, STATIC,   REQUIRED, FLOAT,    IMax,              4) \
X(a, STATIC,   REQUIRED, BOOL,     useAutoHome,       5) \
X(a, STATIC,   REQUIRED, MESSAGE,  home_param,        6) \
X(a, STATIC,   REQUIRED, BOOL,     enableDebug,       7)
#define Setting_ZDT_CALLBACK NULL
#define Setting_ZDT_DEFAULT NULL
#define Setting_ZDT_home_param_MSGTYPE Setting_ZDT_HomeParam

#define Setting_ZDT_HomeParam_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    home_speed,        1) \
X(a, STATIC,   REQUIRED, INT32,    home_timeout,      2) \
X(a, STATIC,   REQUIRED, INT32,    home_collide_speed,   3) \
X(a, STATIC,   REQUIRED, INT32,    home_collide_current,   4) \
X(a, STATIC,   REQUIRED, INT32,    home_collide_time,   5) \
X(a, STATIC,   REQUIRED, INT32,    home_wait_time,    6)
#define Setting_ZDT_HomeParam_CALLBACK NULL
#define Setting_ZDT_HomeParam_DEFAULT NULL

#define Setting_MIT_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    Kp_a,              1) \
X(a, STATIC,   REQUIRED, FLOAT,    Ki_a,              2) \
X(a, STATIC,   REQUIRED, FLOAT,    Kd_a,              3) \
X(a, STATIC,   REQUIRED, FLOAT,    offset_a,          4) \
X(a, STATIC,   REQUIRED, FLOAT,    Kp_b,              5) \
X(a, STATIC,   REQUIRED, FLOAT,    Ki_b,              6) \
X(a, STATIC,   REQUIRED, FLOAT,    Kd_b,              7) \
X(a, STATIC,   REQUIRED, FLOAT,    offset_b,          8) \
X(a, STATIC,   REQUIRED, FLOAT,    Kp_c,              9) \
X(a, STATIC,   REQUIRED, FLOAT,    Ki_c,             10) \
X(a, STATIC,   REQUIRED, FLOAT,    Kd_c,             11) \
X(a, STATIC,   REQUIRED, FLOAT,    offset_c,         12) \
X(a, STATIC,   REQUIRED, FLOAT,    Kp_d,             13) \
X(a, STATIC,   REQUIRED, FLOAT,    Ki_d,             14) \
X(a, STATIC,   REQUIRED, FLOAT,    Kd_d,             15) \
X(a, STATIC,   REQUIRED, FLOAT,    offset_d,         16) \
X(a, STATIC,   REQUIRED, FLOAT,    Kp_e,             17) \
X(a, STATIC,   REQUIRED, FLOAT,    Ki_e,             18) \
X(a, STATIC,   REQUIRED, FLOAT,    Kd_e,             19) \
X(a, STATIC,   REQUIRED, FLOAT,    offset_e,         20) \
X(a, STATIC,   REQUIRED, FLOAT,    Kp_f,             21) \
X(a, STATIC,   REQUIRED, FLOAT,    Ki_f,             22) \
X(a, STATIC,   REQUIRED, FLOAT,    Kd_f,             23) \
X(a, STATIC,   REQUIRED, FLOAT,    offset_f,         24)
#define Setting_MIT_CALLBACK NULL
#define Setting_MIT_DEFAULT NULL

extern const pb_msgdesc_t Setting_msg;
extern const pb_msgdesc_t Setting_Wifi_msg;
extern const pb_msgdesc_t Setting_Servo_msg;
extern const pb_msgdesc_t Setting_Temperature_msg;
extern const pb_msgdesc_t Setting_mDNS_msg;
extern const pb_msgdesc_t Setting_LED_msg;
extern const pb_msgdesc_t Setting_Decoy_msg;
extern const pb_msgdesc_t Setting_ZDT_msg;
extern const pb_msgdesc_t Setting_ZDT_HomeParam_msg;
extern const pb_msgdesc_t Setting_MIT_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Setting_fields &Setting_msg
#define Setting_Wifi_fields &Setting_Wifi_msg
#define Setting_Servo_fields &Setting_Servo_msg
#define Setting_Temperature_fields &Setting_Temperature_msg
#define Setting_mDNS_fields &Setting_mDNS_msg
#define Setting_LED_fields &Setting_LED_msg
#define Setting_Decoy_fields &Setting_Decoy_msg
#define Setting_ZDT_fields &Setting_ZDT_msg
#define Setting_ZDT_HomeParam_fields &Setting_ZDT_HomeParam_msg
#define Setting_MIT_fields &Setting_MIT_msg

/* Maximum encoded size of messages (where known) */
#define PROTO_SETTING_PB_H_MAX_SIZE              Setting_size
#define Setting_Decoy_size                       44
#define Setting_LED_size                         2
#define Setting_MIT_size                         129
#define Setting_Servo_size                       369
#define Setting_Temperature_size                 33
#define Setting_Wifi_size                        332
#define Setting_ZDT_HomeParam_size               66
#define Setting_ZDT_size                         92
#define Setting_mDNS_size                        66
#define Setting_size                             1086

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
