/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_HANDYPLUG_HANDYPLUG_PB_H_INCLUDED
#define PB_HANDYPLUG_HANDYPLUG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _handyplug_Ok {
    uint32_t Id;
} handyplug_Ok;

typedef struct _handyplug_Error {
    uint32_t Id;
    pb_callback_t ErrorMessage;
    int32_t ErrorCode;
} handyplug_Error;

typedef struct _handyplug_Ping {
    uint32_t Id;
} handyplug_Ping;

typedef struct _handyplug_RequestServerInfo {
    uint32_t Id;
    pb_callback_t ClientName;
    uint32_t MessageVersion;
} handyplug_RequestServerInfo;

typedef struct _handyplug_ServerInfo {
    uint32_t Id;
    pb_callback_t ServerName;
    uint32_t MessageVersion;
    uint32_t MaxPingTime;
} handyplug_ServerInfo;

typedef struct _handyplug_LinearCmd {
    uint32_t Id;
    uint32_t DeviceIndex;
    pb_callback_t Vectors;
} handyplug_LinearCmd;

typedef struct _handyplug_LinearCmd_Vector {
    uint32_t Index;
    uint32_t Duration;
    double Position;
} handyplug_LinearCmd_Vector;

typedef struct _handyplug_Message {
    pb_size_t which_Message;
    union _handyplug_Message_Message {
        /* Status Messages */
        handyplug_Ok Ok;
        handyplug_Error Error;
        handyplug_Ping Ping;
        /* Handshake Messages */
        handyplug_RequestServerInfo RequestServerInfo;
        handyplug_ServerInfo ServerInfo;
        /* Generic Device Messages */
        handyplug_LinearCmd LinearCmd;
    } Message;
} handyplug_Message;

typedef struct _handyplug_Payload {
    pb_callback_t Messages;
} handyplug_Payload;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define handyplug_Ok_init_default                {0}
#define handyplug_Error_init_default             {0, {{NULL}, NULL}, 0}
#define handyplug_Ping_init_default              {0}
#define handyplug_RequestServerInfo_init_default {0, {{NULL}, NULL}, 0}
#define handyplug_ServerInfo_init_default        {0, {{NULL}, NULL}, 0, 0}
#define handyplug_LinearCmd_init_default         {0, 0, {{NULL}, NULL}}
#define handyplug_LinearCmd_Vector_init_default  {0, 0, 0}
#define handyplug_Message_init_default           {0, {handyplug_Ok_init_default}}
#define handyplug_Payload_init_default           {{{NULL}, NULL}}
#define handyplug_Ok_init_zero                   {0}
#define handyplug_Error_init_zero                {0, {{NULL}, NULL}, 0}
#define handyplug_Ping_init_zero                 {0}
#define handyplug_RequestServerInfo_init_zero    {0, {{NULL}, NULL}, 0}
#define handyplug_ServerInfo_init_zero           {0, {{NULL}, NULL}, 0, 0}
#define handyplug_LinearCmd_init_zero            {0, 0, {{NULL}, NULL}}
#define handyplug_LinearCmd_Vector_init_zero     {0, 0, 0}
#define handyplug_Message_init_zero              {0, {handyplug_Ok_init_zero}}
#define handyplug_Payload_init_zero              {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define handyplug_Ok_Id_tag                      1
#define handyplug_Error_Id_tag                   1
#define handyplug_Error_ErrorMessage_tag         2
#define handyplug_Error_ErrorCode_tag            3
#define handyplug_Ping_Id_tag                    1
#define handyplug_RequestServerInfo_Id_tag       1
#define handyplug_RequestServerInfo_ClientName_tag 2
#define handyplug_RequestServerInfo_MessageVersion_tag 3
#define handyplug_ServerInfo_Id_tag              1
#define handyplug_ServerInfo_ServerName_tag      2
#define handyplug_ServerInfo_MessageVersion_tag  3
#define handyplug_ServerInfo_MaxPingTime_tag     4
#define handyplug_LinearCmd_Id_tag               1
#define handyplug_LinearCmd_DeviceIndex_tag      2
#define handyplug_LinearCmd_Vectors_tag          3
#define handyplug_LinearCmd_Vector_Index_tag     1
#define handyplug_LinearCmd_Vector_Duration_tag  2
#define handyplug_LinearCmd_Vector_Position_tag  3
#define handyplug_Message_Ok_tag                 100
#define handyplug_Message_Error_tag              101
#define handyplug_Message_Ping_tag               102
#define handyplug_Message_RequestServerInfo_tag  200
#define handyplug_Message_ServerInfo_tag         201
#define handyplug_Message_LinearCmd_tag          403
#define handyplug_Payload_Messages_tag           1

/* Struct field encoding specification for nanopb */
#define handyplug_Ok_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   Id,                1)
#define handyplug_Ok_CALLBACK NULL
#define handyplug_Ok_DEFAULT NULL

#define handyplug_Error_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   Id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   ErrorMessage,      2) \
X(a, STATIC,   SINGULAR, INT32,    ErrorCode,         3)
#define handyplug_Error_CALLBACK pb_default_field_callback
#define handyplug_Error_DEFAULT NULL

#define handyplug_Ping_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   Id,                1)
#define handyplug_Ping_CALLBACK NULL
#define handyplug_Ping_DEFAULT NULL

#define handyplug_RequestServerInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   Id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   ClientName,        2) \
X(a, STATIC,   SINGULAR, UINT32,   MessageVersion,    3)
#define handyplug_RequestServerInfo_CALLBACK pb_default_field_callback
#define handyplug_RequestServerInfo_DEFAULT NULL

#define handyplug_ServerInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   Id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   ServerName,        2) \
X(a, STATIC,   SINGULAR, UINT32,   MessageVersion,    3) \
X(a, STATIC,   SINGULAR, UINT32,   MaxPingTime,       4)
#define handyplug_ServerInfo_CALLBACK pb_default_field_callback
#define handyplug_ServerInfo_DEFAULT NULL

#define handyplug_LinearCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   Id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   DeviceIndex,       2) \
X(a, CALLBACK, REPEATED, MESSAGE,  Vectors,           3)
#define handyplug_LinearCmd_CALLBACK pb_default_field_callback
#define handyplug_LinearCmd_DEFAULT NULL
#define handyplug_LinearCmd_Vectors_MSGTYPE handyplug_LinearCmd_Vector

#define handyplug_LinearCmd_Vector_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   Index,             1) \
X(a, STATIC,   SINGULAR, UINT32,   Duration,          2) \
X(a, STATIC,   SINGULAR, DOUBLE,   Position,          3)
#define handyplug_LinearCmd_Vector_CALLBACK NULL
#define handyplug_LinearCmd_Vector_DEFAULT NULL

#define handyplug_Message_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Message,Ok,Message.Ok), 100) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Message,Error,Message.Error), 101) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Message,Ping,Message.Ping), 102) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Message,RequestServerInfo,Message.RequestServerInfo), 200) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Message,ServerInfo,Message.ServerInfo), 201) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Message,LinearCmd,Message.LinearCmd), 403)
#define handyplug_Message_CALLBACK NULL
#define handyplug_Message_DEFAULT NULL
#define handyplug_Message_Message_Ok_MSGTYPE handyplug_Ok
#define handyplug_Message_Message_Error_MSGTYPE handyplug_Error
#define handyplug_Message_Message_Ping_MSGTYPE handyplug_Ping
#define handyplug_Message_Message_RequestServerInfo_MSGTYPE handyplug_RequestServerInfo
#define handyplug_Message_Message_ServerInfo_MSGTYPE handyplug_ServerInfo
#define handyplug_Message_Message_LinearCmd_MSGTYPE handyplug_LinearCmd

#define handyplug_Payload_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  Messages,          1)
#define handyplug_Payload_CALLBACK pb_default_field_callback
#define handyplug_Payload_DEFAULT NULL
#define handyplug_Payload_Messages_MSGTYPE handyplug_Message

extern const pb_msgdesc_t handyplug_Ok_msg;
extern const pb_msgdesc_t handyplug_Error_msg;
extern const pb_msgdesc_t handyplug_Ping_msg;
extern const pb_msgdesc_t handyplug_RequestServerInfo_msg;
extern const pb_msgdesc_t handyplug_ServerInfo_msg;
extern const pb_msgdesc_t handyplug_LinearCmd_msg;
extern const pb_msgdesc_t handyplug_LinearCmd_Vector_msg;
extern const pb_msgdesc_t handyplug_Message_msg;
extern const pb_msgdesc_t handyplug_Payload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define handyplug_Ok_fields &handyplug_Ok_msg
#define handyplug_Error_fields &handyplug_Error_msg
#define handyplug_Ping_fields &handyplug_Ping_msg
#define handyplug_RequestServerInfo_fields &handyplug_RequestServerInfo_msg
#define handyplug_ServerInfo_fields &handyplug_ServerInfo_msg
#define handyplug_LinearCmd_fields &handyplug_LinearCmd_msg
#define handyplug_LinearCmd_Vector_fields &handyplug_LinearCmd_Vector_msg
#define handyplug_Message_fields &handyplug_Message_msg
#define handyplug_Payload_fields &handyplug_Payload_msg

/* Maximum encoded size of messages (where known) */
/* handyplug_Error_size depends on runtime parameters */
/* handyplug_RequestServerInfo_size depends on runtime parameters */
/* handyplug_ServerInfo_size depends on runtime parameters */
/* handyplug_LinearCmd_size depends on runtime parameters */
/* handyplug_Message_size depends on runtime parameters */
/* handyplug_Payload_size depends on runtime parameters */
#define HANDYPLUG_HANDYPLUG_PB_H_MAX_SIZE        handyplug_LinearCmd_Vector_size
#define handyplug_LinearCmd_Vector_size          21
#define handyplug_Ok_size                        6
#define handyplug_Ping_size                      6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
