/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "main.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_haina_Setting, com_haina_Setting, 2)


PB_BIND(com_haina_Setting_Wifi, com_haina_Setting_Wifi, 2)


PB_BIND(com_haina_Setting_Servo, com_haina_Setting_Servo, AUTO)


PB_BIND(com_haina_Setting_Temperature, com_haina_Setting_Temperature, AUTO)


PB_BIND(com_haina_Setting_mDNS, com_haina_Setting_mDNS, AUTO)


PB_BIND(com_haina_Setting_LED, com_haina_Setting_LED, AUTO)


PB_BIND(com_haina_Setting_Decoy, com_haina_Setting_Decoy, AUTO)


PB_BIND(com_haina_Setting_ZDT, com_haina_Setting_ZDT, AUTO)


PB_BIND(com_haina_Setting_ZDT_HomeParam, com_haina_Setting_ZDT_HomeParam, AUTO)



