/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "proto/setting.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Setting, Setting, 2)


PB_BIND(Setting_Wifi, Setting_Wifi, 2)


PB_BIND(Setting_Servo, Setting_Servo, AUTO)


PB_BIND(Setting_Temperature, Setting_Temperature, AUTO)


PB_BIND(Setting_mDNS, Setting_mDNS, AUTO)


PB_BIND(Setting_LED, Setting_LED, AUTO)


PB_BIND(Setting_Decoy, Setting_Decoy, AUTO)


PB_BIND(Setting_ZDT, Setting_ZDT, AUTO)


PB_BIND(Setting_ZDT_HomeParam, Setting_ZDT_HomeParam, AUTO)


PB_BIND(Setting_MIT, Setting_MIT, AUTO)



